CREATE TABLE ATENDENTES(
	ID_ATENDENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	NASCIMENTO DATE NOT NULL,
	SEXO ENUM('F', 'M') NOT NULL
);