	CREATE TABLE CHAMADOS(
		ID_CHAMADO INT PRIMARY KEY AUTO_INCREMENT,
		STATUS ENUM('ABERTO', 'EM ESPERA', 'FECHADO'),
		ABERTURA DATE NOT NULL,
		FECHAMENTO DATE,
		ID_CLIENTE INT NOT NULL,
		ID_ATENDENTE INT NOT NULL,
		
		FOREIGN KEY(ID_CLIENTE)
		REFERENCES CLIENTES(ID_CLIENTE),
		
		FOREIGN KEY(ID_ATENDENTE)
		REFERENCES ATENDENTES(ID_ATENDENTE)	
	);